#!/usr/bin/python
# -*- coding: utf-8 -*-

#----------------------------------------------------------------------
# This file was generated by C:\home\development\work\work\wx_things\wx_forms.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

rccl = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAB0lJ"
    "REFUWIWdl+lyIzcShD9cjT54SdSM1/v+b7URe3hnrNFI4tV3N479gSYleWxHeCuiSQZJIBJV"
    "mVkF4b2Ps5txzqGkQimFEAIpJX8U0zRRdw1t19H1HVobPu8f2KzWAMQYEUL8sC6EwOwc3nu0"
    "Umij0TFGLnXN8XJCColWmqosWa/WaKU+AJnczDgOHE8nHl++c64vjNNIbgvGaeLT/Z5VWVHk"
    "+W1NjJEQAv3Q0w49ddPQDT2f7vd8ut8nAOf6wpdvj0gh0Erzef9AllmEtR8BzBOXpubx+Yl/"
    "/OdfHE4HZu9Zlyu898QYkEKQW3vLQIwR5x112/B6PvH8+sLxckZKwX53hwYQQiCE4NI2NG3L"
    "5GaElNxtd2xXa4QUBB9oupanl2eeDy90fYdzjhAj4zxyOB3JjKbIC4qiwGYZSirGaaLtGh6/"
    "P/Hl+yNudvgQiCECoK/1VlJStw3/ffyKCw5rDFopVmWFQuK8p2lbvj0/8f3wyjCOhBgRgHMz"
    "x/MRIWG33bHbbFFKIYVknEYuTc3X79/45y//Zl2tblwRCKQQAqUURhukkBAjWmnKosRmFrlk"
    "R8nED60TMCHFbRNIh9BKY7RGa532EmC0xmYWozVKKbRW6XcpEUKkEiipMMakxUpR2JztektZ"
    "lEgpb3+2xlDYHJtZlOxu3BBCYowhz9JvmTGoZY0xhrIo05PnWGMxS3YR70pwRSiWUvzy6xfa"
    "rmW33S4sHjicjrweD3RDjw/hA0Hn2XFpa758+8o4jazKFTYzdH1P0zQcTkfmeUaUYI25yT1l"
    "QMnl9BohJK+nI23b8rDf8/OnnxjGicPxQN0lCc3eQYwIIW9MH8eBg5+o25pfv33j8/4TVVVy"
    "Op85X86cm5phHNhtIpnJUEq9kdAYQ1VW3G93/P3z3/DeA2Azu5gKZFnGWqwo8px4VQ6L1IiJ"
    "1SIZUKYNUkriwqeiKFBaEULk4X7P3XZHYfO0R4wxdkPPMI4cT0eO5xM+hFRbKZBSQIQQYgID"
    "xMS+jxGXF7HQUkiEhBgiIUZiDAgh2VQrNusNq6JkVa1SCYjpmZ2jH3qc94QYCTEQgk+bCYFE"
    "LOwXCMG7DCx5iKkcV/eLRKQQN1BSKnJrWVL4xgHnHcM48Ho68O+vXxjnkRASiPeRAMhFGeID"
    "gLic0vv0Hvm4lghKKbx3FDYZFZAAJAtW2MxSlSVm1vjg+W0EH5i9Y3Yz8zDfuCKlvHmJtRaj"
    "1EcAMWVHKUluc4wxyPcqMNpQFvDz558o8wLvHT68bSBE4sPQ95yamtP5xOvpwDiNEAVZJils"
    "zm6z49P+ge1qnUpw2yJ9kEKwWW/Yrrfk7zNw1eRmtSZfmP8++1cAddMglWaaRo61IsZ43Rtj"
    "DOuy4tP9noe7PfEDgCtBITPZYmTyDYAQiVyZNmiZ9Hm12gUCAN55rLVonSVy3QCmLmqyjNLm"
    "rIryRsy3KqRDXfuOfA8gxqTjaZ6Z3IxWikwnt7pm53rKm2MKuQCL16aS+sXCA0gDiA9JSfPs"
    "mPyMufYLUj/QAH75w/F84vV8pLA5m2pNWRaURZl8+/+IECPTNNKPA6fLmbpr2VRrNqsVRV6g"
    "tX7LQIip339/fSbPcoZh4N7fJdtcGstfBhACbd9xqi88H1441zXxIZJbS2bey1BKtFJ47+m6"
    "jrppOJyPzMGzXq1vaf+r4b3nVJ95fHricD7S9v3brPCeA1JIlFTEGBinidnNgGAYB0IMP2z8"
    "PheLiS7f/ujPziWT64aetu+WgXSZF3ingivhlJLk+YpNteZhd5+Gkj+ZkP8stNLcb+8JIeK8"
    "Z5rm28whF5XdfADSYKKVwlrLqqrIsowQPNM8AzDNM7NzuOAXnS9iW7zfe8c8T/TDAECIAa3T"
    "lJ1nNpFO6R9LcA2lNdbmDMPIl/6RtusZxoHMZAgE7dByupxpuhbn36zaB88wDlyamqfDC5NL"
    "88IcPE1Tc2kbzs0ljWTLcyW1ju/symhNWRR0fc/hcmIYR2Y3Y4wBYJxG2qGjaRtm55Yqp9OP"
    "48i5uSCkoOlaiKnJ1U1N03coKcmvs6FUHzlwjcLm3G/vcM4zuwnvAy/HV3wIOOdw3jF7h5sd"
    "81KWlIFAN/ZMfqbtOowx6ZZ1rbOUrKs1m82GqixvM+YNwDULuc252+5wzjG5kcu5pm4bujGV"
    "4jaosLRjIdI0FAOTm5dRvUZIgdUZeWZZVSuqvGC72fBwv6cqq1v9Y4wfM2CtZSNAK8V6VdF2"
    "PW3X0g4dXd+nZ0hghnHEOUckoqQiszm5tRS2SA5qS8qiYFVWlEVBVVZUZUmZFx+UImKMMYQf"
    "tU6MDNOY9Nt1tH3L6XzmcD5xvBw5nc/0w0iIgcwYVlXFbrPlYXvPbnfHplxRVRVVUZIvV7zf"
    "k/MfAyCRaHap3tMir27o6fqOtm0Z5zSUaK2oijKdMi8oyhJrMjKT3e4A1+vf7wJ4O/THMer9"
    "BRNScwkLIZMnzHjnkVJSFjmZyT6c9Lfrfy/+B80+NktBsK2jAAAAAElFTkSuQmCC")
getrcclData = rccl.GetData
getrcclImage = rccl.GetImage
getrcclBitmap = rccl.GetBitmap
getrcclIcon = rccl.GetIcon

rccl_2 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAB7FJ"
    "REFUWIWtl9tvXEcdxz8z57LnnN31ddeX9bW5OE5I20CABioFqS1IBSReEKoQ8BAQSKjvCMQD"
    "j+U/QAiVB6QKgbgVcFua0Kbk3iSunTSx3Y1jZ+OsL7teX/Z+9pzhYe29xGsugt/LzpmZ3/y+"
    "8/195zezgqfPKFPXePml5/jBmRcplSv89NU3eef6XSxTJ/5wjY6Qzfe/9hwTF6ZZSW/h+woh"
    "BQcHowBsZQv88Dtf4uNHRvjNW1c59/4MCw9TlNwKACeODPHyS8+T3szSF2nn92dvMHHhFpnt"
    "PIKnz6gvnDrGa698j6CtEzAD5PIlsvkiAEIIhBB0tDlsbufxPJ9dU3ikMmtYZohDIwMA5Itl"
    "PM8nXyjV5hmGTld7kJLrYmgauUKJ1EaWV16dQAeIdIYRQnHz9jT9Pb0MxwYJOgEet0hnuNYu"
    "u2UuXL/Krbk7xKJ9dLRZRDq7cSwTgHDQ2uMfMAxSmTQPHi0x3D9E0A4gdwelkKxvZPjT2Qkm"
    "707jVtw9C9SCl8ucvXSem7encF2XhaVF3njvHGvrqX19AOYTC/zhbxPM3Y/jK1WNWwMgJcGg"
    "Q6FU4O+XL/DulYtk8zl8v4FypdjO5XjrwjtM3b0NspoeKTWWV5Z5++K7pNbTqJ3Fd33yhTxX"
    "P7jB62ffILOZwbIsdE3HrXh1AABBJ4gQEhRM3p3mj2//lc3sVm3c8z1uz37I7PxHmIaJaPCV"
    "UpJILnHp5rU9AC7dvMY/blzBrVSQmoZlBtA0yUp66zEAtlMTnUAQ7YriWE49iJDEevpoC4YB"
    "1eiKAmzL4onhUYSoQxNC0NMdIWAYSFENZ5kBdF1nei7RDCDkBNGEhq98RgYG+fyznyNgmk2L"
    "DcUGeWr8Y9XUqOoOlVIgYGz0MIdHDjQBE0Jw7NA4x8eOoQABWJbF7fgSc4sr1VNQT4GDlALf"
    "g+TaKm9fPM/J40/R2dZBsVRiLZNi7v489xMLSCmbSVAQX5ynVC4yfuAwvdFewk6QfLHAnfgs"
    "c/fjO4ggYAbQ9OrGmgDYARuExK0UcSsu79+6yYNkgpHYMOlMmuTaCoVisZbzalxVA1Byy2zM"
    "bjI7H6cnEmWgt5+V1CoPk4/wfR8hJVIKTMPA31FQEwDTMPnkU09TyBcQQqAQ4Pv4vkd3Ryfd"
    "nV07m2iUX7MWQFRBKfAqHtGuCD3d0ZqPkJKe7gjL6eJeALqu8cyTJ6n4XlOI/6cJITANk4cr"
    "ib0AAKZmPmRh6UFVsYL6Bhvbu9+wl4D9xnb8g47DsydPkVhZbw1gK7dFfHEeKSVil05oaoOo"
    "HzX1+HFUNbpVAwKBQCmfSGcEpRTL6c3WANpD7dgBB7FfDgSgfFzPBxSi4SQLIdCkbKCg2Xzl"
    "Ew6FMHQD22pxCgCOHR5nJDa4T/RqkOXUKm++d65pl1JKTh4/wdGDY/9SP4ZpoGmSRDLTGoBj"
    "WTjW3pus0Qql4t5OBSHbIdrV3VQJW9l2rsjUXFWEcu9wK1U9NkO1nrNff6P5vs92rkhiOQ20"
    "YGB9I8PMfJxjh8boaOv4twv+J6aUolAq8uHcDAHTJNI1UNPuHgak1LgTn2Hi/Fnii/NUKpX/"
    "GUBydZVzl85z/tpFdF1rGtvDgK7pBEyLRPIRq+k0T44d5ZkTJwk5wf86sFupMD1zm+u3JtnK"
    "ZpGapD3cTjK1QWYrB7RgQNM0bMtGSoHrllnfylDxHmdBgBA7Pzs1Yee70ZRSbGxvsZ3LAmBo"
    "BrblcHnqHo/WNlozIKUgaDsopRjuG+TF0y+02L2qFaB6oVJ79GsaBs9/5jSWGeDKB9exLQvb"
    "siiVK7gVbx8GpEbQsUHByODQPtTvc8xk6/6RgSEMwyDkBJFobGznqXheawaEEDiWg5Qak3du"
    "0d/Ty0BPP6Jhcc9vLUzf86l4lYYyDblCniuT1ykWC4RD1Vd1seyy+9TUAVIbWTazecJBCykl"
    "tm2h6ZJsPsfv3vwzjm2jSVmr8p5Xqea86e3nc236BpN3p+t3ge9TKpcolMsAhIMhfOVTLLu1"
    "mqEDXJ66x+vvTvHdr55Glxqd4Q56uiKsrK1RcsvVx6SQ7Ca5+hKu1vxdDSigWCqRLxRq4JQC"
    "X3kYukF7uI1YtLfKlF8HrgNs5wpMzj6gVK6g2xq9kShfeeGLJFdXuHtvjoWHCXKFLFJoaJrc"
    "t9TuXka+8qn4HqZhMNA7wNGDYwzFhmgLhii6HsVSPYW6JgSeUlz+IM7S6gZjI71omkbICXJ4"
    "9ACHRp5gfTPD7HycuYV7rGcyeL5XBaEar1yF8gVCKtpCbRwYHuXYoTFiPf1NgJeT6zxIpusA"
    "ol1hllObzNxPcmkqzkC0o+lvmRCC7o4uPvuJT3Pi6HEerS6zuJQgsbzExuYmpXIZTddpD4WJ"
    "9fYzHBtkqC9Ge7itKXA2XyRfLPOtH/+CqdlEff1v/ujn6ld/uQzAkdFeTp88wtdfPMX4aB9t"
    "IZtCqUx7yEbT6iXUrbhkczlWU2s8XEkS6eoi1tNHOBgmYJq1wMnUJmvr26ytb/Hrt97HsU1+"
    "9tt3cF2vzsBoLMru62N2cZXZxVVem7jCaCxKZ3uQrrYgz31qnG98+RTbuRK2ZRDpCFMoKTra"
    "exk/NNZSDxcmP+LbP/klc4srrcRSa/4TXW1DXrsNJUEAAAAASUVORK5CYII=")
getrccl_2Data = rccl_2.GetData
getrccl_2Image = rccl_2.GetImage
getrccl_2Bitmap = rccl_2.GetBitmap
getrccl_2Icon = rccl_2.GetIcon

xls = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAchJ"
    "REFUWIXNV9F1wyAMPNkexJtANskiDaJdJKPAKB4kVT9S/DAWMY7z0p5fHomM4LgTPELU9ajB"
    "XT6k+nIH/OcX1d4NW8nOuWOTew/5vgl1vUqiOzR6I5gZ8n1T1ezc5UPkchOtZTC89yBP1bYF"
    "1toqiYFx7IkxriY0xqi/mRnMvLSDmQUM2YvWPGaev4cQ7nmAUNeDuh5dWgmAlcQ5ynie1wpj"
    "zMqO2QIHt5IX/r4LvPeLeN7XRrs5MZFeK3cSjFmmJGmK1dq8TwhhJXtLLIQgAGRhgTgBeYI4"
    "qRZdOheesUDDUA6UkyBP6uQlAW0naDEVZTXnctfsyHfBUQsWCpQrrilRKnAEMwFtF9RI5H0D"
    "wiELBm1VWyTSEZzyypMvxqjGNhUQdz+qHdyihV/bkwgEhKaV1kBgSFnhTYm/hKy1zTm5KjFG"
    "WGvRs2VmMCgSTvHU3CYlzuMZxhiM4zh/pmlaxcZxXJCZpgnX6xVDzffWp2WlWnxWcutKllvz"
    "qLKNMepkNQLJgqE64oOJcmgVvwe7CbSi+Rx4xcCaCpoFLyHwagvecit+hJdZ0Bor1dpF4IjU"
    "Nfx/C5pvNk/i4UlY+zv1NgLvwJ/XwA8+93WHRIZmhAAAAABJRU5ErkJggg==")
getxlsData = xls.GetData
getxlsImage = xls.GetImage
getxlsBitmap = xls.GetBitmap
getxlsIcon = xls.GetIcon

